// Episode data (generated by scripts/build_timeline.mjs from
// episodes/ml-algorithms/{cues,captions.source,narration-words.raw}.json).
// The visual system never hard-codes seconds: every beat comes from these files.
import type { Caption } from "@remotion/captions";
import captionsJson from "../../../episodes/ml-algorithms/captions.json";
import wordCaptionsJson from "../../../episodes/ml-algorithms/captions.remotion.json";
import timelineJson from "../../../episodes/ml-algorithms/timeline.json";
import { makeCue, type CaptionPhrase, type EpisodeTimeline } from "../../lib/timeline";

export const timeline = timelineJson as unknown as EpisodeTimeline;
export const captions = captionsJson as CaptionPhrase[];
/** Word-level captions in Remotion's standard Caption format (interop / Caption editor). */
export const wordCaptions = wordCaptionsJson as Caption[];
export const cue = makeCue(timeline);

/** Small Latin series tag, top-left HUD. */
export const HUD_TAG = "ML — EP.02";
/** Channel handle on the end card (text only, brand fonts; no logo artwork exists). */
export const CHANNEL_HANDLE = "@anas.theengineer";

/** The five algorithms, in narration order. `gist` = the one idea each chapter leaves. */
export const ALGOS = [
  { id: "linear", name: "Linear Regression", gist: "توقّع رقم" },
  { id: "logistic", name: "Logistic Regression", gist: "تصنيف" },
  { id: "tree", name: "Decision Tree", gist: "أسئلة متتالية" },
  { id: "forest", name: "Random Forest", gist: "متوسط التوقّعات" },
  { id: "kmeans", name: "K-Means", gist: "مجموعات بلا تصنيف" },
] as const;

/** Chapter cue (the spoken ordinal «أولًا» …) and title cue (the English name) per algorithm. */
export const ALGO_CUES = [
  { chapter: "lin.chapter", title: "lin.title" },
  { chapter: "log.chapter", title: "log.title" },
  { chapter: "tree.chapter", title: "tree.title" },
  { chapter: "forest.chapter", title: "forest.title" },
  { chapter: "km.chapter", title: "km.title" },
] as const;

// ---------------------------------------------------------------------------
// Illustrative numbers (fictional, labelled «مثال توضيحي» on screen). One
// apartment runs through Linear Regression, Decision Tree and Random Forest.

export const APARTMENT = { area: 120, rooms: 3 };

/** Known apartments: area (m²) → price (thousands). Fitted line: price = 1.25·area + 10. */
export const LINEAR = {
  points: [
    [45, 62],
    [55, 82],
    [70, 94],
    [80, 112],
    [95, 124],
    [105, 141],
    [140, 181],
    [152, 202],
  ] as Array<[number, number]>,
  line: (area: number) => 1.25 * area + 10,
  xRange: [30, 170] as [number, number],
  yRange: [40, 240] as [number, number],
  estimate: 160_000,
};

export const SPAM = { probability: 0.87, threshold: 0.5 };

export const TREE = {
  q1: { text: "أكبر من", value: "100", unit: "م²؟" },
  q2: "أكثر من غرفتين؟",
  leaves: { no1: 90_000, no2: 130_000, yes: 160_000 },
};

/** Three different trees, same apartment, different predictions → their average. */
export const FOREST = { predictions: [150_000, 160_000, 170_000], average: 160_000 };

export const fmt = (n: number) => n.toLocaleString("en-US");

// ---------------------------------------------------------------------------
// K-Means on 21 fictional customers (x = number of purchases, y = spending,
// both normalised 0..1). Points never move; only centroids and colours do.
// Lloyd's algorithm is run here, deterministically, from fixed initial centroids.

export const CUSTOMERS: Array<[number, number]> = [
  [0.12, 0.18], [0.2, 0.11], [0.27, 0.25], [0.16, 0.31], [0.31, 0.15], [0.22, 0.22], [0.09, 0.26],
  [0.68, 0.36], [0.79, 0.46], [0.85, 0.37], [0.72, 0.51], [0.89, 0.49], [0.76, 0.29], [0.65, 0.45],
  [0.36, 0.78], [0.46, 0.87], [0.53, 0.75], [0.4, 0.69], [0.29, 0.86], [0.49, 0.94], [0.58, 0.84],
];
const INIT_CENTROIDS: Array<[number, number]> = [
  [0.45, 0.45],
  [0.6, 0.3],
  [0.3, 0.6],
];

const nearest = (p: [number, number], cs: Array<[number, number]>) => {
  let best = 0;
  let bd = Infinity;
  cs.forEach((c, k) => {
    const d = (p[0] - c[0]) ** 2 + (p[1] - c[1]) ** 2;
    if (d < bd) {
      bd = d;
      best = k;
    }
  });
  return best;
};

const runKMeans = () => {
  const centroids: Array<Array<[number, number]>> = [INIT_CENTROIDS];
  const assigns: number[][] = [];
  for (let it = 0; it < 6; it++) {
    const cs = centroids[centroids.length - 1];
    const a = CUSTOMERS.map((p) => nearest(p, cs));
    assigns.push(a);
    const next = cs.map((c, k) => {
      const mine = CUSTOMERS.filter((_, i) => a[i] === k);
      if (!mine.length) return c;
      return [mine.reduce((s, p) => s + p[0], 0) / mine.length, mine.reduce((s, p) => s + p[1], 0) / mine.length] as [number, number];
    });
    if (next.every((c, k) => Math.abs(c[0] - cs[k][0]) < 1e-9 && Math.abs(c[1] - cs[k][1]) < 1e-9)) break;
    centroids.push(next);
  }
  return { centroids, assigns };
};

/** centroids[s] = positions after s updates; assigns[s] = assignment to centroids[s]. */
export const KMEANS = runKMeans();
