// Episode data (generated by scripts/build_timeline.mjs from
// episodes/mcp/{cues,captions.source,narration-words.raw}.json). The visual
// system never hard-codes seconds: every beat comes from these files.
import type { Caption } from "@remotion/captions";
import captionsJson from "../../../episodes/mcp/captions.json";
import wordCaptionsJson from "../../../episodes/mcp/captions.remotion.json";
import timelineJson from "../../../episodes/mcp/timeline.json";
import { makeCue, type CaptionPhrase, type EpisodeTimeline } from "../../lib/timeline";

export const timeline = timelineJson as unknown as EpisodeTimeline;
export const captions = captionsJson as CaptionPhrase[];
/** Word-level captions in Remotion's standard Caption format (interop / Caption editor). */
export const wordCaptions = wordCaptionsJson as Caption[];
export const cue = makeCue(timeline);

/** Frame at which a chapter starts. */
export const chapterAt = (id: string) => {
  const c = timeline.chapters.find((ch) => ch.id === id);
  if (!c) throw new Error(`Unknown chapter ${id}`);
  return c.frame;
};

// Illustrative content shown on screen (fictional, labelled «مثال توضيحي»).
export const EXAMPLE = {
  request: "لخّص مبيعات هذا الأسبوع من نظام الشركة",
  tool: "get_weekly_sales",
  toolArabic: "جلب مبيعات الأسبوع",
  data: [
    { k: "الطلبات", v: "124" },
    { k: "الإيرادات", v: "48,200" },
    { k: "مقارنة بالأسبوع الماضي", v: "+12%" },
  ],
  summary: "المبيعات أعلى بـ 12% من الأسبوع الماضي",
  permission: "قراءة المبيعات فقط",
};
